[package]
name = "oxide-example"
version = "0.1.0"
authors = ["gegy1000 <gegy1000@gmail.com>"]

[lib]
name = "oxide_example"
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
oxide = { path = "../../.." }
